name: trustless
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 
  cloud_firestore: ^4.13.6
  provider:
  url_launcher:
  cupertino_icons: ^1.0.2
  image: ^3.0.2
  intl: ^0.18.1
  metamask: ^0.0.2
  lottie:
  walletconnect_dart: 
  flutter_web3: ^2.1.6
  flutter_web3_provider: ^1.0.6
  file_picker: ^5.2.2
  crypto: ^3.0.2
  flutter_svg:
  flutter_markdown:
  http: ^0.13.6
  graphite: ^0.3.0
  emojis: ^0.9.9
  animated_text_kit: ^4.1.1
  flutter_vector_icons: ^1.0.0
  google_fonts: 
  scrollable_positioned_list: ^0.2.2
  universal_html: ^2.0.8
  gojs: ^2.0.0
  dio:
  flutter_expandable_fab: ^2.0.0
  flutter_chat_ui: 
  webviewx: ^0.2.1
  web3dart: ^2.0.0
  ext_video_player: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: fonts/CascadiaCode.ttf
    - family: CascadiaMono
      fonts:
        - asset: fonts/CascadiaMono.ttf